---
- name: Copy the redis_exporter systemd service file
  template:
    src: redis_exporter.service.j2
    dest: /etc/systemd/system/redis_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart redis_exporter

- debug:
    msg: "User: {{ redis_exporter_system_user }}"

- name: Ensure redis_exporter is enabled and started
  ansible.builtin.service:
    name: redis_exporter
    enabled: yes
    state: started
  become: true